// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UAS_DOTNET.data;

namespace UAS_DOTNET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220409132418_tb_sikap")]
    partial class tb_sikap
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("UAS_DOTNET.Models.DbEkstrakurikuler", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama_Ekstrakurikuler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.HasIndex("NIS");

                    b.ToTable("Tb_Ekstrakurikuler");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbKehadiran", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Izin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sakit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tanpa_Keterangan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.HasIndex("NIS");

                    b.ToTable("Tb_Kehadiran");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbMataPelajaran", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Bahasa_Indonesia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matematika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PJOK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PPKN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pendidikan_Agama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.HasIndex("NIS");

                    b.ToTable("Tb_Mata_Pelajaran");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbPrestasi", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jenis_Prestasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.HasIndex("NIS");

                    b.ToTable("Tb_Prestasi");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbSikap", b =>
                {
                    b.Property<string>("Nomor")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Deskripsi_Sikap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Nomor");

                    b.HasIndex("NIS");

                    b.ToTable("Tb_Sikap");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.Guru", b =>
                {
                    b.Property<string>("NUPTK")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Mata_Pelajaran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NUPTK");

                    b.ToTable("Tb_Guru");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.Siswa", b =>
                {
                    b.Property<string>("NIS")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Jenis_Kelamin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NISN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NIS");

                    b.ToTable("Tb_Siswa");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("Username");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_User");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbEkstrakurikuler", b =>
                {
                    b.HasOne("UAS_DOTNET.Models.Siswa", "fkNIS")
                        .WithMany()
                        .HasForeignKey("NIS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkNIS");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbKehadiran", b =>
                {
                    b.HasOne("UAS_DOTNET.Models.Siswa", "fkNIS")
                        .WithMany()
                        .HasForeignKey("NIS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkNIS");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbMataPelajaran", b =>
                {
                    b.HasOne("UAS_DOTNET.Models.Siswa", "fkNIS")
                        .WithMany()
                        .HasForeignKey("NIS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkNIS");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbPrestasi", b =>
                {
                    b.HasOne("UAS_DOTNET.Models.Siswa", "fkNIS")
                        .WithMany()
                        .HasForeignKey("NIS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkNIS");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.DbSikap", b =>
                {
                    b.HasOne("UAS_DOTNET.Models.Siswa", "fkNIS")
                        .WithMany()
                        .HasForeignKey("NIS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fkNIS");
                });

            modelBuilder.Entity("UAS_DOTNET.Models.User", b =>
                {
                    b.HasOne("UAS_DOTNET.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
